env: "local" # server environment
storage_path: "./storage/storage.db"

salt: 4 # bcrypt
secret: "34jfQ" # jwt 

min_required_role: 3 # min required role to get user's personal data
public_files_path: "upload/public"
protected_files_path: "upload/protected"

redis_server:
  host: "redis"
  port: 9000
http_server:
  host: "localhost"
  port: 8000
allow_origin:
  host: "localhost"
  port: 5000