env: "local"
storage_path: "./storage/storage.db"
salt: 4
secret: "34jfQ"
redis_server:
  host: "localhost"
  port: 9500
http_server:
  host: "localhost"
  port: 8000
allow_origin:
  host: "localhost"
  port: 5000