env: "local"
storage_path: "./storage/storage.db"

salt: 4 # bcrypt
secret: "34jfQ" # jwt 

min_required_role: 3 # min required role to get user's personal data
booking_files_path: "upload/protected/booking"
user_files_path: "upload/protected/user"
public_files_path: "upload/public"

redis_server:
  host: "localhost"
  port: 9500
http_server:
  host: "localhost"
  port: 8000
allow_origin:
  host: "localhost"
  port: 5000